from pages.Page import Page
from pages.elements import Row
from pages.elements import RText, Radio, Select, Text, Checkbox
import utilities.xpath as xpath
  
  
class SCR0081(Page):
    """
    SCR_0081 Edit Approval
    """
    locators = {
        "documents": "event=RepositoryLinkEvent",
        "cancel": "ApprovalEditCancelEvent",
        "approval type": xpath.text_sibling("td", "Approval type", 2),
        "generated by": xpath.text_sibling("td", "Generated by", 2),
        "generation date": "xpath=//span[contains(normalize-space(text()), 'Generation date')]/../following-sibling::td[2]",
        "due date": "name=approvalEventOrDateRadio",
        "due date event": "name=dueDateEventId",
        "due date date": "name=dueDate",
        "status": "name=approvalStatusId",
        "coi status": "name=conflictStatusId",
        "responsible party": xpath.text_sibling("td", "Responsible party", 2),
        "approval/assurance number": "name=approvalNumber",
        "multiples required": "name=multipleApprovals",
        "received": "xpath=//span[contains(normalize-space(text()), 'Received')]/../following-sibling::td[2]",
        "effective": "xpath=//span[contains(normalize-space(text()), 'Effective')]/../following-sibling::td[2]",
        "expires": "xpath=//span[contains(normalize-space(text()), 'Expires')]/../following-sibling::td[2]",
        "comments": xpath.text_sibling("td", "Comments", 2),
        "Approval_link": "xpath=//a[contains(text(),'Human participation IRB')]",
        "approval": "xapth=//nav[@id='segment-navigation']/ul/li[7]/a"
    }
     
    _loactors = {
        "Approval_link": "xpath=//a[contains(text(),'Human participation IRB')]",
        "approval": "xapth=//nav[@id='segment-navigation']/ul/li[7]/a",
        "edit": "xpath=//button[@id='editButton']",
        "generated date": "xpath=//span[contains(normalize-space(text()), 'Generated date')]/../following-sibling::td[1]",
        "due date": "xpath=//span[contains(normalize-space(text()), 'Due event')]/../following-sibling::td[1]",
        "status": "xpath=//span[contains(normalize-space(text()), 'Status')]/../following-sibling::td[1]",
        "responsible party": "xpath=//span[contains(normalize-space(text()), 'Responsible party')]/../following-sibling::td[1]",
        "approval number": "xpath=//span[contains(normalize-space(text()), 'Approval/Assurance number')]/../following-sibling::td[1]",
        "date effective": "xpath=//span[contains(normalize-space(text()), 'Date effective')]/../following-sibling::td[1]",
        "date expires":  "xpath=//span[contains(normalize-space(text()), 'Date expires')]/../following-sibling::td[1]",
        "documents": "xpath=//div[@id='j_idt160_header']/ul/li"
        }
      
    documents = RText("documents", "Documents")
    approval_type = RText("approval type", "Approval Type")
    generated_by = RText("generated by", "Generated by")
    generation_date = RText("generation date", "Generation date")
    due_date = Radio("due date", "Due date") 
    duedate_event = Select("due date event", "Due date - event")
    duedate_date = Text("due date date", "Due date - date")
    status = Select("status", "Status")
    coi_status = Select("coi status", "Conflict of interest status") 
    responsible_party = RText("responsible party", "Responsible party")
    approval_number = Text("approval/assurance number", "Approval/assurance number")
    multiples_required = Checkbox("multiples required", "Multiples required")
    received  = RText("received", "Received date")
    effective = RText("effective", "Effe