from pages.Page import Page
from pages.elements import RText, Radio
import utilities.xpath as xpath

class SCR0653(Page):
    """
    SCR_0653 
    """
    locators = {
    "current OAR certification status": "xpath=//*[contains(normalize-space(text()), 'Current OAR certification status')]/./following::td[1]",
    "reserach certification status": "xpath=//*[contains(normalize-space(text()), 'Research certification status:')]/./following::td[1]",
    "ceritification last updated": "xpath=//*[contains(normalize-space(text()), 'Certification last updated:')]/./following::td[1]",
    "approval generated by": "xpath=//*[contains(normalize-space(text()), 'Generated by:')]/./following::td[1]",
    "approval generated date": "xpath=//*[contains(normalize-space(text()), 'Generated date:')]/./following::td[1]",
    "comments": "id=commentsCountId",
    "documents": "xpath=//*[contains(normalize-space(text()), 'Documents')]/./following::td[1]"   
    }
    
    @classmethod
    def url(cls, HUID, segmentId, segment_revision_id,approval_requirement_id):
        """
        Direct navigation to SCR_0653
        """
        url = "{{}}/gmas/dispatch?segmentScopeRequestId=&ApprovalListViewOrEditDetailEvent=&requestTypeId=&responsiblePartyDisplayString=Dubreuil%2C+Catherine+Irene&HUID={}&approvalTypeId=2022&ref=%2Fapproval%2FSCR0080Approvals.jsp&fromSegmentHomePage=true&requestId=&formName=ApprovalListForm&segmentId={}&segmentRevisionId={}&approvalId={}&approvalUserId=&generatedBy=&submit"
        return url.format(HUID, segmentId, segment_revision_id, approval_requirement_id)

    
    OAR_status = RText("current OAR certification status", "Current OAR certification status")
    research_status = RText("reserach certification status", "Reserach certification status")
    certification_update = RText("ceritification last updated", "Ceritification last updated")
    generated_by = RText("approval generated by", "Approval generated by")
    generated_date = RText("approval generated date", "Approval generated date")
    comments = RText("comments", "Comments")
    documents = RText("documents", "Documents")


