from pages.Page import Page
from pages.elements import Row, RText
import utilities.xpath as xpath

class SCR0644(Page):
    """
    SCR_0644 COI Approval
    """
    locators = {
        "status": "css=select[name='approvalStatusId']",
        "FCOI participant": xpath.text_sibling("td", "FCOI participant:", 2),
        "disclosure on file": xpath.text_sibling("td", "Disclosure on File", 2),
        "date received": xpath.text_sibling("td", "Date Received", 2),
        "interests": "//table[@id='tb']/tbody/tr[12]/td[4]",
        "generated by": xpath.text_sibling("td", "Generated By:", 2),
        "generation date": "xpath=//span[contains(normalize-space(text()), 'Generation Date:')]/../following-sibling::td[2]",
        "reason generated": xpath.text_sibling("td", "Reason Generated", 2),
        "approval row": "xpath=//td[contains(text(), 'Approval Status History')]/./following::tr[6]",
        "comments": xpath.text_sibling("td", "Comments", 2),
        "documents": "xpath=//*[contains(normalize-space(text()), 'Documents')]/../following-sibling::td[2]",
        "COI": "link=Conflict of Interest"
    }
    
    _locators = {
        "status": "xpath=//span[contains(normalize-space(text()), 'Status')]/../following-sibling::td[1]",
        "FCOI participant": "xpath=//span[contains(normalize-space(text()), 'FCOI participant')]/../following-sibling::td[1]",
        "disclosure on file": "xpath=//span[contains(normalize-space(text()), 'Disclosure on file')]/../following-sibling::td[1]",
        "date received": "xpath=//span[contains(normalize-space(text()), 'Date received')]/../following-sibling::td[1]",
        "generated by": "xpath=//span[contains(normalize-space(text()), 'Generated by')]/../following-sibling::td[1]",
        "generation date": "xpath=//span[contains(normalize-space(text()), 'Generated date')]/../following-sibling::td[1]",
        "reason generated": "xpath=//span[contains(normalize-space(text()), 'Reason generated')]/../following-sibling::td[1]",
        "approval row": "css=[id$=j_idt149_content] tbody tr",
        "documents": "xpath=//div[@id='documentsPanel_header']/ul/li/span",
        "COI": "link=Conflict of Interest"
    }
    
    
    status = RText("status", "Current approval status")
    FCOI_participant = RText("FCOI participant", "FCOI participant")
    disclosureon_file = RText("disclosure on file", "Disclosure on file")
    date_received = RText("date received", "Approval date received")
    generated_by = RText("generated by", "Approval generated by")
    generation_date = RText("generation date", "Approval generation date")
    reason_generated = RText("reason generated", "Approval reason generated")
    documents = RText("documents", "Documents")
    
        
    @classmethod
    def url(cls, request_id, segment_Id, huid, approval_requirement_id):
        """
        Direct navigation to SCR_0644
        """
        url = "{{}}/gmas/dispatch?ApprovalListViewOrEditDetailEvent=&requestTypeId=&requestId={}&segmentId={}&formName=ApprovalListForm&approvalTypeId=2021&HUID={}&approvalId={}&generatedBy=&ref=%2Fapproval%2FSCR0080Approvals.jsp&segmentScopeRequestId=&fromSegmentHomePage=true&responsiblePartyDisplayString=Bjerregaard%2C+Peter&approvalUserId=&segmentRevisionId=&submit"
        return url.format(request_id, segment_Id, huid, approval_requirement_id)

    def goto_documents(self):
        """
        Clicks the "Documents" link
        Goes to SCR_0433
        """
        return self.go("documents")
    
    @property
    def documents(self):
        if self.mode == "old":
            return self.find("documents").text.split(" ")[0:1]
        if self.mode == "convert":
            return self.find("documents").text
    
    def goto_coi(self):
        """
        Click "Conflict of interest"
        """
        self.find("COI").click()

    @property
    def approval_rows(self):
        """
        List of all rows from the "approval status history" table
        """
        return [self.Approval_row(row, self) for row in self.finds("approval row")]

    class Approval_row(Row):
        locators = {
            "date": Row.cell(3),
            "status": Row.cell(6),
            "updated by": Row.cell(9)
        }
        
        _locators = {
            "date": Row.cell(1),
            "status": Row.cell(2),
            "updated by": Row.cell(3)          
        }

        date = RText("date", "Approval date")
        status = RText("status", "Approval status")
        updated_by = RText("updated by", "Approval updated by")
        
    
